name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build examples and tests
      run: |
        rm -rf build || true
        mkdir -p build
        cd build
        cmake .. -DLIBMBUS_BUILD_EXAMPLES=ON -DLIBMBUS_BUILD_TESTS=ON -DLIBMBUS_ENABLE_COVERAGE=ON && cmake --build . -j
        cd ..

    - name: generate test frames
      run: |
        ./test/generate-xml.sh test/test-frames
        echo "NOTE: error-frames have about 30 parse errors, and unsupported-frames have 12"
        ./test/generate-xml.sh test/error-frames || true
        ./test/generate-xml.sh test/unsupported-frames || true

    - name: install and run gcovr
      run: sudo pip install gcovr && gcovr build/.

  debian:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build debian package
      run: |
        rm -rf build || true
        mkdir -p build
        cd build
        cmake .. -DLIBMBUS_PACKAGE_DEB=ON
        cpack ..
        sudo dpkg -i *.deb
        ls /usr/lib

  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build doxygen documentation
      run: sudo apt install -y doxygen
      
    - name: build doxygen documentation
      run: |
        rm -rf build || true
        mkdir build
        cd build
        cmake .. -DLIBMBUS_BUILD_DOCS=ON
        cmake --build . --target doc
